# These settings are synced to GitHub by https://probot.github.io/apps/settings/
repository:
  name: asdf-chezmoi
  description: chezmoi plugin for asdf version manager
  topics: asdf, asdf-plugin, chezmoi
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: true
  allow_update_branch: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
- name: main
  protection:
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    required_status_checks:
      strict: true
      checks:
      - context: pre-commit.ci - pr
        app_id: 68672
      - context: Semantic PR
        app_id: 198092
      - context: DCO
        app_id: 1861
      - context: asdf plugin test (ubuntu-latest)
        app_id: 15368
      - context: asdf plugin test (macos-latest)
        app_id: 15368
    enforce_admins: false
    required_linear_history: true
    restrictions:
